-- =============================================
-- Seed: Default Super Admin User
-- Username: gem
-- Password: admin123
-- Created: 2026-02-11
-- =============================================

-- Insert default super admin user
-- Password: #Admin123 (hashed with bcrypt, rounds=10)
INSERT INTO users (username, password, role) 
VALUES (
    'gem',
    '$2a$12$pNKp955py0QIbpD.6Hdg9.EXOYNncWX.nTHtuUT7igi9ez1t6ZuLC',  -- This is a placeholder hash
    'superAdmin'
)
ON CONFLICT (username) DO NOTHING;

-- Note: The actual bcrypt hash for 'admin123' will be generated by the application
-- This placeholder should be replaced when running the seed for the first time
-- Or you can use the application's seed command to generate the correct hash

COMMENT ON TABLE users IS 'Default super admin created: username=gem, password=#Admin123';